stage('Continuous Deployment') {
  steps {
    sshagent(['ssh_key']) {
      script {
        def remoteCommands = """
          cd /home/ubuntu/ &&
          wget -O docker-compose.yml https://raw.githubusercontent.com/Shreyash-jiwane09/DLProject/main/docker-compose.yml &&
          export IMAGE_NAME=${ECR_REPOSITORY}:latest &&
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com &&
          docker compose pull &&
          docker compose up -d
        """

        sh """
          ssh -o StrictHostKeyChecking=no -l ubuntu 43.205.14.255 "${remoteCommands}"
        """
      }
    }
  }
}
